# .streamlit/secrets.toml

# ✅ DADOS VINDOS DO ARQUIVO serviceAccountKey.json
[firebase_service_account]
type = "service_account"
project_id = "siga-a16ff"
private_key_id = "1ee85255c3b1bfcb58c7663199052ed2b687d05c"
client_email = "firebase-adminsdk-fbsvc@siga-a16ff.iam.gserviceaccount.com"
client_id = "106297330115191802100"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40siga-a16ff.iam.gserviceaccount.com"

# IMPORTANTE: A private_key precisa estar entre aspas triplas
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCGJKo1h3L3YBnl\ndgjRRGLLLpoLAWUeg+VG1OGUYJ2Niu2XfWgJdxplJiSPHg9SBT5u8RqLXVgKmSWC\ngss5pj4O7F27QJ+QpdiTZOeQOA3NznHRNqNAI+jxOkH21xg2F1Ysk4dfVOfvvcrg\nFwYyoOKzfC6j6cS38O9gQR3u2Ja55b8n5teNClCbUdr61j4u4rvRjUXedhrd3x9C\ne+cdNIHnf7qlnO3PPxhHeVG2IWSX4hXu0T7cwbuvLZNnean+kmgc7JzeychgaGKB\nLyvl7fjDIqcmQazC0kFQrtK2th0rUV8S+CYkrk2Ih3cpzgpSfbadnKMyVQAWBAMT\nuXyKM24xAgMBAAECgf9aQdFEsx5n1AGYoxLLu3e9vl1niki/f3+FaTde3qMj2ZaD\nl52owLrB1ChFI7SrO1wGybNSkjvq5aCXb+nNoE2hPOjUVWcHrI9MnVgxcYXYNE/g\ntSKixYa2yLwZmiBwRMN2us0bF8X3SXx3ywYgip/+pE+9ek0idrqZyTaavqCr8zCB\nBPhmX8JbSyuppafgIR0rSI1ZL1tVYEk6ZzeYptTAJFehaFw4gEZYS7rjjZmu3/+/\nwI0uddQZd/b0r8OR+Rk88+HMktR/Mz0aHtdQB0cA4hbg/KQCE1NZE/aEFAD8ackd\nEx1qpbAAeUggCFplmJPOBtjmTSfYvVf+OcrtLp0CgYEAvKtCfF6BHJIFrhW1OgEm\n37BUn3LmxzkKFuEKi5SE1Vktrx5GRN3daDTdGo/xVqtDFoRAOis3i1gNisuIlGNt\nKcdWCqGPZI42YVTiYjwWz5PqGURAdnLLVi/oth7mPEEOAt3CsEfbwfcxNDoZ33Mq\nBNw747IqmRbGGELMvNX+bhUCgYEAtgPyysSAyuphUEHqqvjrzk9ySJfLNqKg1nAG\nD13H7tZxHhKrwmOni+Owiho/rPgtCCYy8LpwiWya7BylVSGqwG+FTSCvPLQN/EPq\nyEbUbSGbP9a+rNhv8Y7lmmjvbmGnpbxKTKIZW2p0rcvwZDJCRQmtD92TeD1yZRUv\n8mFjYq0CgYBC4uxFLzPSryn4V5XSJIpljxvRE2khg+VByzJz3YliIaWCidcbnxRZ\nVzRzsEg9E6ZLG0Ox25RrgCH87L9U7BLNVu/4AOLXIVvCEdfYP7lOif/aSUoZNAVG\nXuG/fyDch6ux9HCLEk6ka0A0Zcy6XReudW1+AbH8aAh+nV/8KllzKQKBgGtn/xC6\nTknvbwdeLm0/wF6ZMRY3RLpz0zdXGaxdqcp9jnixiduG1OrOrHGCNcsLE/+4Et1N\nF3VwuibUbJfE6y7tYBr4S5AlrA8NwPD4IwhXCXbtcM0sVzqTGVg5zfgz9irt5mY8\nTXxNYJbiPnPR2JtGr3IqTYhpsiSGESoVYAFtAoGBAJM7e1M7qwCBsEBBKbak/1El\nJi3hwlMxGz0glCCRmxEedzFycU1Ph2z455jGaapfvWWSGPmKXUvaNv3gipZknZdS\nzMf5hhO5JUYzzpQ12I+hsMfHcU91s3p9eJyQriV0aN1rAMDpbnSkhN6TzhMjstQL\n70E93jHDCYShyHbZ/kZY\n-----END PRIVATE KEY-----"""


# ✅ DADOS VINDOS DO CONSOLE DO FIREBASE (Configurações do Projeto > Geral > Seus Apps)
[firebase_web_config]
apiKey = "AIzaSyB3mVK8DDqrZpBYoQNrn5MP_87miSmiE6w"
authDomain = "siga-a16ff.firebaseapp.com"
projectId = "siga-a16ff"
storageBucket = "siga-a16ff.appspot.com"
messagingSenderId = "COLE_SEU_SENDER_ID_AQUI"
appId = "269196845331"
databaseURL = ""